# Generated by Django 5.0.1 on 2025-12-06 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('picked-up', 'Picked Up'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bicycles.bicycle')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate at time of rental', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pickup_notes', models.TextField(blank=True, help_text='Condition at pickup')),
                ('return_notes', models.TextField(blank=True, help_text='Condition at return')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Distance traveled in KM', max_digits=8)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='bicycles.bicycle')),
                ('pickup_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rentals', to='stations.station')),
                ('return_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_rentals', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental', to='rentals.reservation')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='rentals_res_user_id_608f98_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['bicycle', 'status'], name='rentals_res_bicycle_419396_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'expires_at'], name='rentals_res_status_485d93_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['user', 'status'], name='rentals_ren_user_id_cc9157_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['bicycle', 'status'], name='rentals_ren_bicycle_928704_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status', 'start_time'], name='rentals_ren_status_6b9402_idx'),
        ),
    ]
