# Generated by Django 5.0.1 on 2025-12-06 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code (e.g., LIB, ENG)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude', max_digits=9, null=True)),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Maximum number of bicycles', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.CharField(default='24/7', help_text="e.g., '6:00 AM - 10:00 PM' or '24/7'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='stations_st_code_03b933_idx'), models.Index(fields=['is_active'], name='stations_st_is_acti_1d477b_idx')],
            },
        ),
    ]
