# Generated by Django 5.0.1 on 2025-12-06 20:20

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bicycles/', validators=[core.validators.validate_file_size])),
                ('frame_size', models.CharField(blank=True, help_text='e.g., M, L, XL', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('gear_count', models.PositiveIntegerField(default=1, help_text='Number of gears')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50.0, help_text='Hourly rental rate in KES', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('total_rentals', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Total distance traveled in KM', max_digits=10)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bicycles', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='bicycles.bicycle')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bicycle',
            index=models.Index(fields=['status', 'current_station'], name='bicycles_bi_status_5cee6e_idx'),
        ),
        migrations.AddIndex(
            model_name='bicycle',
            index=models.Index(fields=['serial_number'], name='bicycles_bi_serial__ea0f75_idx'),
        ),
        migrations.AddIndex(
            model_name='bicycle',
            index=models.Index(fields=['slug'], name='bicycles_bi_slug_449d32_idx'),
        ),
    ]
